version: '3.8'

services:
  qdrant_test:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "7333:6333"  # Different port to avoid conflicts with dev
      - "7334:6334"
    environment:
      - QDRANT_ALLOW_ORIGIN=*
    tmpfs:
      - /qdrant/storage  # Use in-memory storage for tests
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  neo4j_test:
    image: neo4j:5.15.0
    ports:
      - "8474:7474"  # Different port to avoid conflicts with dev
      - "8687:7687"
    environment:
      - NEO4J_AUTH=neo4j/twincore_test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      # Use in-memory mode for tests - updated for Neo4j 5.x
      - NEO4J_server_memory_pagecache_size=100M
      - NEO4J_server_memory_heap_initial__size=100M
      - NEO4J_server_memory_heap_max__size=500M
    tmpfs:
      - /data
      - /logs
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s 